### ISSUE TITLE
activeTextEditor might undefined, not null

### ISSUE THREAD

**Issue by jrieken** [mitaki28/vscode-clang#10]
I stumbled over [this](https://github.com/mitaki28/vscode-clang/blob/master/src/extension.ts#L76) and just fyi the editor won't be `null` but `undefined`. Also, using `registerTextEditorCommand` might be more convenient for your use-case.

**Comment by mitaki28** [comment]
Thank you for your advice.
I've used 	`registerTextEditorCommand` for `clang.showExecConf` instead of `registerCommand`.
