### ISSUE TITLE
Go to Definition does not work

### ISSUE THREAD

**Issue by dvirsky** [mitaki28/vscode-clang#11]
I'm not sure it's the responsibility of this extension, if isn't I'll close. 
But everything works fine, completion etc - but go to definition simply doesn't, even in the same file.

**Comment by dodjango** [comment]
I can reproduce this. Making it work would be very helpful.

**Comment by dvirsky** [comment]
@dodjango just use the MS C/C++ plugin that has this working (though not perfectly - they tend to open duplicate instances of the same file)

**Comment by dodjango** [comment]
Thx!
