### ISSUE TITLE
Adding new include folders

### ISSUE THREAD

**Issue by decarvalhorobinson** [mitaki28/vscode-clang#20]
I am using cmake and VScode on windows and I can´t find a way to make clang extension recognize my include folder to autocomplete. I have the glfw source file inside my project and I am building with cmake, everything is fine, but clang cant read the glfw/include folder.

**Comment by mitaki28** [comment]
Please use `clang.cflags` (for C sources) or `clang.cxxflags` (for C++ sources) in configuration. ( [README.md#Configuration](https://github.com/mitaki28/vscode-clang/blob/master/README.md#configuration))
 `-I` compiler option enable you to specify an include directory. (http://clang.llvm.org/docs/CommandGuide/clang.html#cmdoption-I)

Please note that if you specify `glfw/include` as a relative path from your workspace root, you need to use `workspaceRoot` variable and specify `-I${workspaceRoot}/glfw/include`. ([README.md#Variables](https://github.com/mitaki28/vscode-clang/blob/master/README.md#variables))

**Comment by decarvalhorobinson** [comment]
It worked perfectly, thanks so much. I am trying to use vscode intead of the Visual Studio, and I am having a hard time to read a lot of thing to get the configurations done. Linking libraries is being a pain in the ass. Thanks for spending some time to help me.  :octocat:
