### ISSUE TITLE
Project relative clang.flags

### ISSUE THREAD

**Issue by csholmq** [mitaki28/vscode-clang#3]
Any way to achieve project relative paths with the user config `clang.cflags`? 

`"clang.cflags": ["-I../out/obj"]` works fine for one tree level, but I want the same for files on deeper levels. I tried an absolute path, hoping that it would be relative to project root, but that didn't work (not way for Clang to know that path obviously).

Sorted back to `"clang.cflags": ["-I../out/obj","-I../../out/obj"]` which seems like an ugly hack. Any ideas?

**Comment by mitaki28** [comment]
Now, configurations support some variables which are available in `tasks.json`.
Please update this extension.
You can use `${workspaceRoot}` in `clang.cflags`.

Please note that `${workspaceRoot}` have no trailing slash, so you need to specify `-I${workspaceRoot}/out/obj`, not `-I${workspaceRoot}out/obj`

**Comment by csholmq** [comment]
That's excellent! Also, I realized that I can also utilize workspace configuration in each project root. Should also do the trick!
