### ISSUE TITLE
Not recognize C++11 lambda expression

### ISSUE THREAD

**Issue by renkun-ken** [mitaki28/vscode-clang#31]
VSCode: 1.5.2
OS: Ubuntu 16.04.1
Extension: 0.2.1

I'm writing C++ 11 code and use lambda in my code. The following code is a simple example:

```cpp
#include <iostream>

int main(int argc, char** argv)
{
    std::cout << "hello, world!" << std::endl;
    const int x = 0;
    const auto f = [&x](int i) { return x + i; };
    std::cout << f(10) << std::endl;
    return 0;
}
```

The code compiles perfectly with `gcc` and `clang` but in VSCode it produces the following warnings and errors:

1. 'auto' type specifier is a C++11 extension [-Wc++11-extension] (7, 11)
2. expected expression (7, 20)

Below is a screenshot of this:

![main cpp - cpptest - visual studio code_088](https://cloud.githubusercontent.com/assets/4662568/18409965/2757ae5e-7788-11e6-87db-84ccc24637e0.png)

**Comment by San0from** [comment]
# It's work good for me :
>VSCode: 1.5.2
>OS: Ubuntu 16.04.1
>Extension: 0.2.1

* same code

could you show me your config for C/C++ Clang?

It's mine:

	// Compiler options for C (e.g. ['-std=c99'])
	"clang.cflags": ["-std=c99"],

	// Compiler options for C++ (e.g. ['-std=c++11'])
	"clang.cxxflags": ["-std=c++11"],

check if you set **-std=c++11** for your **clang.cxxflags** in *"user settings"* or *"workspace settings"*

**Comment by renkun-ken** [comment]
Thanks! With `"clang.cxxflags": ["-std=c++11"]`, it works for me now.

**Comment by Ridge2** [comment]
Or you can just type: `g++ main.cpp -Wall -std=c++0x -o main`
Then: `./main` to run the program.
