### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by emKaroly** [mitaki28/vscode-clang#34]
I would like to know how this extension compare to [Microsoft C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). What is same whats different can i use both?

**Comment by meritozh** [comment]
Currently, [Microsoft C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) force on debug, Its autocomplete feature is just under experimental.

And this extension has a great autocomplete experience.

**Comment by jake4679** [comment]
This plugin does not appear to work anymore.

**Comment by runapp** [comment]
Yes. Looking forward for updates.   --- from one who failed to develop one's own plugin

**Comment by r44083** [comment]
I confirm that plugin works well.
