### ISSUE TITLE
`. clang_complete` Support broken / missing?

### ISSUE THREAD

**Issue by boazsegev** [mitaki28/vscode-clang#55]
The common way to add `clang` development flags to projects (for linting / auto-complete) is by using the `.clang_complete`.

These files allow us to share project specific flags between different development environments (`vim`, Atom, etc').

However, I tried using this extension in a project where this file is used to list the location of the `include` files is sub-folders (i.e. `-Isrc/http/`)...

...but the extension doesn't seem to recognize the flags in the `.clang_complete` file.

VSCode Version 1.12.2 (1.12.2)
vscode-clang version 0.2.2
macOS 10.12.5

**Comment by boazsegev** [comment]
I suspect this might be related to the fact that the `.clang_complete` file is in the root of the project (along with the `makefile` etc') while the code being reviewed is nested within the `/src` folder and it's subfolders.

Could it be that the package ignores `.clang_complete` files in parent folders?

**Comment by trond-snekvik** [comment]
Have you tried passing `@.clang_complete` as a compiler argument? It should read the variables from the file, [like GCC does](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html)

**Comment by boazsegev** [comment]
That's a cool idea... even though it sounds like a workaround rather than a solution ;-)

**Comment by boazsegev** [comment]
Obsolete?
