### ISSUE TITLE
False positive of error: "c++17 invalid value in --std=c++17"

### ISSUE THREAD

**Issue by Zenohate** [mitaki28/vscode-clang#63]
## Step to reproduce:

1. In a c++ project
2. add the following in Workspace settings
```json
{
	"clang.cxxflags": [
		"--std=c++17"
	]
}
```
3. open an editor in a valid C++ file

## VSCODE:

* Version 1.20.1
* Commit f88bbf9137d24d36d968ea6b2911786bfe103002
* Date 2018-02-13T15:31:18.341Z
* Shell 1.7.9
* Renderer 58.0.3029.110
* Node 7.9.0
* Architecture ia32

## Extension

* Version: 0.2.2

## `clang -v`:

```
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: i686-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.2.0
Selected GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0
Candidate multilib: .;@m32
Candidate multilib: 64;@m64
Candidate multilib: x32;@mx32
Selected multilib: .;@m32
```

## OS:

Debian 9 32bit

**Comment by jonasdmentia** [comment]
That error isn't a false positive, it's correct. clang's c++17 support began with 5.0, so 3.8 doesn't recognize --std=c+17. It does have some pre-standard support which you can enable with --std=c++1z. 

For details see [here](https://clang.llvm.org/cxx_status.html).

**Comment by davydden** [comment]
@jonasdmentia a bit off-topic, but the `Contributions` tab of `vscode-clangd` does not list `clang.cxxflags` as an option. Has something changed recently?

**Comment by jonasdmentia** [comment]
@davydden, not according to the commit history...if anything it looks a bit dead as it's not been touched in a year. That said, my `Contributions` tab still lists `clang.cxxflags`. I'm running vscode 1.21.1 with vscode-clangd 0.2.2

**Comment by davydden** [comment]
ah, sorry, I mixed this GitHub repository `vscode-clang` with `LLVM's` plugin `vscode-clagd` https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd with version `0.0.5`.
