### ISSUE TITLE
Suggestions after '>'

### ISSUE THREAD

**Issue by KyleMayes** [mitaki28/vscode-clang#8]
Opening the suggestions list after typing `>` makes it rather annoying to type templates because hitting <kbd>return</kbd> selects the first entry in the list rather than create a newline as one would expect.

It would be nice if this was disabled or at least made an option. Thanks for the great plugin!

![vscode-c](https://cloud.githubusercontent.com/assets/1016104/13473657/4b754dec-e088-11e5-8aa3-35e09aee946a.png)

**Comment by csholmq** [comment]
Workaround (https://github.com/Microsoft/vscode-go/issues/103#issuecomment-183390915)

`keybindings.json`
```
{
    "key": "enter",
    "when" : "editorTextFocus && suggestWidgetVisible"
}
```

**Comment by mitaki28** [comment]
@KyleMayes 
I have add new configuration `clang.completion.triggerChars`. 
Now, we can disable completion on hitting `'>'` key.

**Comment by csholmq** [comment]
Also, with https://github.com/Microsoft/vscode/commit/1fa8bcdf9db61e6ed65929ff956ac6c1e10ca67c you now have the option `editor.acceptSuggestionOnEnter: false` to disable Enter as a user. Will be available in next VSCode release.
