### ISSUE TITLE
autocomplete works incorrectly in linux kernel codes

### ISSUE THREAD

**Issue by abadcafe** [mitaki28/vscode-clang#9]
it gives wrong function name suggestions in most files.

my workspace settings: 
```json
// Place your settings in this file to overwrite default and user settings.
{
    "clang.cxxflags": ["-I${workspaceRoot}/include"],
    "clang.cflags": ["-I${workspaceRoot}/include"]
}
```

**Comment by mitaki28** [comment]
I cannot reproduce this issue because of insufficient information. 
Please tell me following information:

1.  the version of your clang, vscode and vscode-clang
2.  a source code, completion position and completion items on the occurrence of this issue
    - taking a screenshot is a good way.

Thank you.

**Comment by abadcafe** [comment]
@mitaki28 

as my workspace settings, open fs/block_dev.c in the linux kernel, I can get struct members complete, but no function completes.

in fact, every c file in the linux kernel are works the same.

`
// Place your settings in this file to overwrite default and user settings.
{
    "clang.cxxflags": ["-I${workspaceRoot}/include"],
    "clang.cflags": ["-I${workspaceRoot}/include"]
}
`

**Comment by csholmq** [comment]
@abadcafe You were too quick to post there. Your screenshot never finished the upload.

**Comment by abadcafe** [comment]
sorry for that.

**Comment by mitaki28** [comment]
@abadcafe 

Thank you for your detail report. I confirmed that this issue occurs.

This issue seems to be caused by insufficient size of buffer for communicating with clang process.
Now, I have increased default buffer size and added option for changing buffer size (d868884).

**Comment by abadcafe** [comment]
@mitaki28 since 0.2.0, this bug was resolved. good job!
